_wandb:
    value:
        cli_version: 0.22.0
        e:
            jyztd6jz6k5hs4gras7du6xstgid1whp:
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "254634999808"
                        used: "247292665856"
                email: adey004azeez@gmail.com
                executable: C:\Users\USER\anaconda3\python.exe
                git:
                    commit: 877f052727b47d84245a51a4b5053f59796583be
                    remote: https://github.com/Adeyemi-authentic/breast-classification.git
                host: DESKTOP-O1H15VD
                memory:
                    total: "8464732160"
                os: Windows-10-10.0.19045-SP0
                program: breastclassif/Breast classifiation with pytorch.ipynb
                python: CPython 3.11.5
                root: C:\Users\USER\breastclassif
                startedAt: "2025-10-16T16:24:27.039457Z"
                writerId: jyztd6jz6k5hs4gras7du6xstgid1whp
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.11.5
            "5": 0.22.0
            "8":
                - 1
                - 3
            "12": 0.22.0
            "13": windows-amd64
        visualize:
            confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
class_weight:
    value: balanced
criterion:
    value: gini
max_depth:
    value: 20
max_features:
    value: sqrt
min_samples_split:
    value: 2
model:
    value: RandomForest
